# Change these first
owner: LukeIsHereToDevelop # Your GitHub username
repo: Services-Status # Your GitHub repository name

# Add your sites here
sites:
  - name: Website
    url: https://lukedev.tk
  - name: API
    url: https://api.lukedev.tk

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.lukedev.tk
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://cdn.discordapp.com/avatars/427464899883433984/a_947db4b0e6cd92d8e5ef7af5a50f2dbc.gif
  name: LukeDev's Services Status
  introTitle: "Services **Status**."
  introMessage: This **Status Page** provides **Real-Time** data about my services.
  navbar:
    - title: Status
      href: /
    - title: Main Website
      href: https://lukedev.tk
    - title: API
      href: https://api.lukedev.tk
    - title: GitHub
      href: https://github.com/$OWNER/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
